image: python:latest

before_script:
  - apt-get update -qy
  - apt-get install -qy locales
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

cache:
  paths:
  - ~/.cache/pip/

test:
  type: build
  script:
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - python server.py &

staging:
  type: deploy
  only:
  - dev
  script:
  - L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
  - flynn cluster add -p $FLYNN_CERTIFICATE_PIN $FLYNN_CLUSTER_NAME $FLYNN_CONTROLLER_DOMAIN $FLYNN_CONTROLLER_KEY
  - flynn create -y $CI_PROJECT_NAME || true
  - git push -f flynn HEAD:dev


production:
  image: ruby:latest
  type: deploy
  only:
  - master
  script:
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=sand-ws-conformance-server --api-key=$HEROKU_PRODUCTION_API_KEY
